<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProductVersion>10.0.0</ProductVersion>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\ICSharpCode.NRefactory.snk</AssemblyOriginatorKeyFile>
    <NoWin32Manifest>False</NoWin32Manifest>
    <NoStdLib>False</NoStdLib>
    <IntermediateOutputPath>obj\$(Configuration)\</IntermediateOutputPath>
    <DocumentationFile>$(IntermediateOutputPath)ICSharpCode.NRefactory.Cecil.xml</DocumentationFile>
    <NoWarn>1591</NoWarn>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>Full</DebugType>
    <OutputPath>..\bin\Debug</OutputPath>
    <ConsolePause>false</ConsolePause>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>PdbOnly</DebugType>
    <OutputPath>..\bin\Release</OutputPath>
    <ConsolePause>false</ConsolePause>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'net_4_5_Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>Full</DebugType>
    <Optimize>False</Optimize>
    <OutputPath>..\bin\Debug</OutputPath>
    <ConsolePause>false</ConsolePause>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'net_4_5_Release|AnyCPU' ">
    <DebugType>PdbOnly</DebugType>
    <Optimize>True</Optimize>
    <OutputPath>..\bin\Release</OutputPath>
    <ConsolePause>false</ConsolePause>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>DEBUG;</DefineConstants>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'net_4_5_Debug' ">
    <DefineConstants>DEBUG;</DefineConstants>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Platform)' == 'AnyCPU' ">
    <BaseAddress>4194304</BaseAddress>
    <RegisterForComInterop>False</RegisterForComInterop>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
    <FileAlignment>4096</FileAlignment>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'net_4_5_Release' ">
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <NuGetVersionCecil Condition="$(NuGetVersionCecil) == ''">0.10.1</NuGetVersionCecil>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="$(NuGetVersionCecil)" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\ICSharpCode.NRefactory\Properties\GlobalAssemblyInfo.cs" Link="Properties\GlobalAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ICSharpCode.NRefactory\ICSharpCode.NRefactory.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="obj\net_4_5_Debug\.NETFramework,Version=v4.5.AssemblyAttributes.cs" />
    <Compile Remove="obj\net_4_5_Release\.NETFramework,Version=v4.5.AssemblyAttributes.cs" />
  </ItemGroup>
</Project>